# yaml-language-server: $schema=https://cdn.jsdelivr.net/npm/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: luckyyjdev/blog
  branch: master
  base_url: https://sveltia-cms-auth.1918176773.workers.dev

media_folder: /static/images
public_folder: /images

locale: "zh-CN"

collections:
  - name: posts
    label: 文章
    label_singular: 文章
    folder: /content/posts
    create: true
    format: toml-frontmatter
    extension: md
    slug: "{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime, type: date }
      - { label: 草稿, name: draft, widget: boolean, default: true }
      - { label: 标签, name: tags, widget: list }
      - { label: 分类, name: categories, widget: list }
      - { label: 摘要, name: summary, widget: text, required: false }
      - { label: 正文, name: body, widget: markdown }
